--insert into "{TARGETSCHEMA}"."Acl" select * from "{SOURCESCHEMA}"."Acl";
--insert into "{TARGETSCHEMA}"."AdjustmentType" select * from "{SOURCESCHEMA}"."AdjustmentType";
insert into "{TARGETSCHEMA}"."Age" select * from "{SOURCESCHEMA}"."Age" where "CompanyId" = {COMPANYID};
insert into "{TARGETSCHEMA}"."AgeBand" select "AgeBand".* from "{SOURCESCHEMA}"."AgeBand" join "{SOURCESCHEMA}"."CompanyCoverageTier" on ( "CompanyCoverageTier"."Id" = "AgeBand"."CompanyCoverageTierId" ) where "CompanyCoverageTier"."CompanyId" = {COMPANYID};
--insert into "{TARGETSCHEMA}"."AgeType" select * from "{SOURCESCHEMA}"."AgeType";
--insert into "{TARGETSCHEMA}"."Audit" select * from "{SOURCESCHEMA}"."Audit" where "CompanyId" = {COMPANYID};
insert into "{TARGETSCHEMA}"."AutomaticAdjustment" select * from "{SOURCESCHEMA}"."AutomaticAdjustment" where "CompanyId" = {COMPANYID};
--insert into "{TARGETSCHEMA}"."BackgroundTask" select * from "{SOURCESCHEMA}"."BackgroundTask";
insert into "{TARGETSCHEMA}"."CompanyParent" select "CompanyParent".* from "{SOURCESCHEMA}"."CompanyParent" join "{SOURCESCHEMA}"."CompanyParentCompanyRelationship" on ( "CompanyParentCompanyRelationship"."CompanyParentId" = "CompanyParent"."Id" ) where "CompanyParentCompanyRelationship"."CompanyId" = {COMPANYID};
insert into "{TARGETSCHEMA}"."CompanyParentCompanyRelationship" select * from "{SOURCESCHEMA}"."CompanyParentCompanyRelationship" where "CompanyId" = {COMPANYID};
insert into "{TARGETSCHEMA}"."Company" select * from "{SOURCESCHEMA}"."Company" where "Id" = {COMPANYID};
insert into "{TARGETSCHEMA}"."CompanyCarrier" select * from "{SOURCESCHEMA}"."CompanyCarrier" where "CompanyId" = {COMPANYID};
insert into "{TARGETSCHEMA}"."CompanyCoverageTier" select * from "{SOURCESCHEMA}"."CompanyCoverageTier" where "CompanyId" = {COMPANYID};
insert into "{TARGETSCHEMA}"."CompanyLife" select * from "{SOURCESCHEMA}"."CompanyLife" where "CompanyId" = {COMPANYID};
insert into "{TARGETSCHEMA}"."CompanyLifeCompare" select * from "{SOURCESCHEMA}"."CompanyLifeCompare" where "CompanyId" = {COMPANYID};
insert into "{TARGETSCHEMA}"."CompanyLifeDiff" select * from "{SOURCESCHEMA}"."CompanyLifeDiff" where "CompanyId" = {COMPANYID};
insert into "{TARGETSCHEMA}"."CompanyLifeResearch" select * from "{SOURCESCHEMA}"."CompanyLifeResearch" where "CompanyId" = {COMPANYID};
insert into "{TARGETSCHEMA}"."CompanyPlan" select * from "{SOURCESCHEMA}"."CompanyPlan" where "CompanyId" = {COMPANYID};
insert into "{TARGETSCHEMA}"."CompanyPlanType" select * from "{SOURCESCHEMA}"."CompanyPlanType" where "CompanyId" = {COMPANYID};
insert into "{TARGETSCHEMA}"."CompanyPreference" select * from "{SOURCESCHEMA}"."CompanyPreference" where "CompanyId" = {COMPANYID};
insert into "{TARGETSCHEMA}"."CompanyRelationship" select * from "{SOURCESCHEMA}"."CompanyRelationship" where "CompanyId" = {COMPANYID};
insert into "{TARGETSCHEMA}"."CompanyReport" select * from "{SOURCESCHEMA}"."CompanyReport" where "CompanyId" = {COMPANYID};
--insert into "{TARGETSCHEMA}"."HistoryChangetoCompany" select * from "{SOURCESCHEMA}"."HistoryChangeToCompany";
--insert into "{TARGETSCHEMA}"."HistoryFailedJob" select * from "{SOURCESCHEMA}"."HistoryFailedJob";
insert into "{TARGETSCHEMA}"."ImportData" select * from "{SOURCESCHEMA}"."ImportData" where "CompanyId" = {COMPANYID};
insert into "{TARGETSCHEMA}"."LifeData" select * from "{SOURCESCHEMA}"."LifeData" where "CompanyId" = {COMPANYID};
insert into "{TARGETSCHEMA}"."LifeEventCompare" select * from "{SOURCESCHEMA}"."LifeEventCompare" where "CompanyId" = {COMPANYID};
--insert into "{TARGETSCHEMA}"."Log" select * from "{SOURCESCHEMA}"."Log" where "CompanyId" = {COMPANYID};
insert into "{TARGETSCHEMA}"."ManualAdjustment" select * from "{SOURCESCHEMA}"."ManualAdjustment" where "CompanyId" = {COMPANYID};
--insert into "{TARGETSCHEMA}"."MappingColumnHeaders" select * from "{SOURCESCHEMA}"."MappingColumnHeaders";
--insert into "{TARGETSCHEMA}"."MappingColumns" select * from "{SOURCESCHEMA}"."MappingColumns";
--insert into "{TARGETSCHEMA}"."PlanTypes" select * from "{SOURCESCHEMA}"."PlanTypes";
--insert into "{TARGETSCHEMA}"."ProcessQueue" select * from "{SOURCESCHEMA}"."ProcessQueue";
--insert into "{TARGETSCHEMA}"."Relationship" select * from "{SOURCESCHEMA}"."Relationship";
insert into "{TARGETSCHEMA}"."RelationshipData" select * from "{SOURCESCHEMA}"."RelationshipData" where "CompanyId" = {COMPANYID};
--insert into "{TARGETSCHEMA}"."RelationshipMapping" select * from "{SOURCESCHEMA}"."RelationshipMapping";
insert into "{TARGETSCHEMA}"."ReportReviewWarnings" select * from "{SOURCESCHEMA}"."ReportReviewWarnings" where "CompanyId" = {COMPANYID};
--insert into "{TARGETSCHEMA}"."ReportType" select * from "{SOURCESCHEMA}"."ReportType";
insert into "{TARGETSCHEMA}"."RetroData" select * from "{SOURCESCHEMA}"."RetroData" where "CompanyId" = {COMPANYID};
insert into "{TARGETSCHEMA}"."RetroDataLifeEvent" select * from "{SOURCESCHEMA}"."RetroDataLifeEvent" where "CompanyId" = {COMPANYID};
--insert into "{TARGETSCHEMA}"."RetroRules" select * from "{SOURCESCHEMA}"."RetroRules";
--insert into "{TARGETSCHEMA}"."SchemaChangeLog" select * from "{SOURCESCHEMA}"."SchemaChangeLog";
insert into "{TARGETSCHEMA}"."SummaryData" select * from "{SOURCESCHEMA}"."SummaryData" where "CompanyId" = {COMPANYID};
insert into "{TARGETSCHEMA}"."SummaryDataPremiumEquivalent" select * from "{SOURCESCHEMA}"."SummaryDataPremiumEquivalent" where "CompanyId" = {COMPANYID};
insert into "{TARGETSCHEMA}"."SummaryDataYTD" select * from "{SOURCESCHEMA}"."SummaryDataYTD" where "CompanyId" = {COMPANYID};
insert into "{TARGETSCHEMA}"."User" select "User".* from "{SOURCESCHEMA}"."User" join "{SOURCESCHEMA}"."UserCompany" on ( "UserCompany"."UserId" = "User"."Id" ) where "UserCompany"."CompanyId" = {COMPANYID};
insert into "{TARGETSCHEMA}"."UserCompany" select * from "{SOURCESCHEMA}"."UserCompany" where "CompanyId" = {COMPANYID};
insert into "{TARGETSCHEMA}"."UserPreference" select "UserPreference".* from "{SOURCESCHEMA}"."UserPreference" join "{SOURCESCHEMA}"."UserCompany" on ( "UserCompany"."UserId" = "UserPreference"."UserId" ) where "UserCompany"."CompanyId" = {COMPANYID};
insert into "{TARGETSCHEMA}"."ValidationErrors" select * from "{SOURCESCHEMA}"."ValidationErrors" where "CompanyId" = {COMPANYID};
--insert into "{TARGETSCHEMA}"."Verbiage" select * from "{SOURCESCHEMA}"."Verbiage";
--insert into "{TARGETSCHEMA}"."WashRules" select * from "{SOURCESCHEMA}"."WashRules";
insert into "{TARGETSCHEMA}"."WashedData" select * from "{SOURCESCHEMA}"."WashedData" where "CompanyId" = {COMPANYID};
insert into "{TARGETSCHEMA}"."Wizard" select * from "{SOURCESCHEMA}"."Wizard" where "CompanyId" = {COMPANYID};
